apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-risky-exec-pods
  annotations:
    policies.kyverno.io/title: Getting shell on pods
    policies.kyverno.io/category: RBAC
    policies.kyverno.io/severity: High
    policies.kyverno.io/minversion: 1.12.0
    kyverno.io/kyverno-version: 1.12.0
    kyverno.io/kubernetes-version: "1.22-1.23"
    policies.kyverno.io/subject: ClusterRoleBinding
    policies.kyverno.io/description: >-

spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: risky-exec-pods-clusterrole
      match:
        any:
        - resources:
            kinds:
            - ClusterRoleBinding
      context:
        - name: role
          apiCall:
            urlPath: "/apis/rbac.authorization.k8s.io/v1/clusterroles/{{ request.object.roleRef.name }}"
      validate:
        message: >- 
           ClusterRoleBinding "{{ request.object.metadata.name }}" with subjects {{ request.object.subjects[].name }}
           is using role {{role.metadata.name}}
        deny:
          conditions:
            any:
              - key: "{{ ( contains(role.rules[].verbs[], 'create') || contains(role.rules[].verbs[], 'get')) && (contains(role.rules[].resources[], 'pods/exec') || contains(role.rules[].resources[], 'pod')) && contains(role.rules[].apiGroups[], '*') }}"
                operator: Equals
                value: true
    - name: risky-exec-pods-roles
      match:
        any:
          - resources:
              kinds:
                - RoleBinding
      preconditions:
        any:
        - key: "{{ request.object.roleRef.kind || 'ClusterRole' }}"
          operator: NotEquals
          value: ClusterRole
      context:
        - name: role
          apiCall:
            urlPath: "/apis/rbac.authorization.k8s.io/v1/namespaces/{{ request.object.metadata.namespace }}/roles/{{ request.object.roleRef.name }}"
      validate:
        message: >- 
           RoleBinding {{ request.object.metadata.name }} with subjects {{ request.object.subjects[].name }} 
           is using role {{role.metadata.name}}
        deny:
          conditions:
            any:
              - key: "{{ ( contains(role.rules[].verbs[], 'create') || contains(role.rules[].verbs[], 'get')) && (contains(role.rules[].resources[], 'pods/exec') || contains(role.rules[].resources[], 'pod')) && contains(role.rules[].apiGroups[], '*') }}"
                operator: Equals
                value: true
